Add bulk check permissions test
authzed/authzed-rb pull request #132
Opened 2024-10-02 18:24 UTC by tstirrat15

Fixes #131 

## Description
There wasn't a test validating that `check_bulk_permissions` works, or example usage of `check_bulk_permissions`. This addresses the first and partially addresses the second.

## Changes
* Add new test
* Add .ruby-version file for rvm etc
* Bump buf.gen.yaml to v2
* Bump some deps
## Testing
Review. See that things pass.

2024-10-02 18:27 UTC, alecmerdler submitted a review, later dismissed

2024-10-03 06:32 UTC, vroldanbet reviewed
running `buf generate` works for me. running the buf YAML file as a script throws an error

```
Failure: :2:1 unknown field "version", expected one of [file]
   2 | version: "v2"
   2 | ^

:3:1 unknown field "plugins", expected one of [file]
   3 | plugins:
   3 | ^

:8:1 unknown field "inputs", expected one of [file]
   8 | inputs:
   8 | ^
```

2024-10-03 06:35 UTC, vroldanbet requested changes
Please add ` --template` back to the buf yaml 🙏🏻

2024-10-03 06:36 UTC, vroldanbet approved these changes

2024-10-03 09:16 UTC, merged