fix: adds runtime dependencies to authzed
authzed/authzed-rb pull request #23
Opened 2022-06-08 14:56 UTC by stevendaniels

+ Adds missing dependencies. Without runtime dependencies, authzed will not run properly:

```
 require 'authzed'
LoadError: cannot load such file -- google/protobuf
from /Users/somedev/.rbenv/versions/2.7.1/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
Caused by LoadError: cannot load such file -- authzed
from /Users/somedev/.rbenv/versions/2.7.1/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
```

2022-06-08 19:22 UTC, stevendaniels commented
I have read the CLA Document and I hereby sign the CLA

2022-06-14 05:04 UTC, samkim requested changes
Could you add `gemspec` to the Gemfile and remove the grpc and grpc-tools lines from Gemfile as well to avoid redundant definitions? Otherwise looks good!

2022-06-24 22:02 UTC, stevendaniels commented
Updated. Can you recheck?

2022-06-27 16:46 UTC, samkim approved these changes
LGTM

2022-06-27 16:55 UTC, merged